name: macos

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-10.15

    steps:
      - run: git clone https://github.com/jopohl/urh && cd urh && git checkout apicheck

      #- name: Install SDR libs
      #  run: |
      #    brew tap pothosware/homebrew-pothos
      #    brew update

      - name: Build libiio
        run: |
          wget -nv https://github.com/analogdevicesinc/libiio/archive/refs/tags/v0.23.tar.gz -O iio.tar.gz
          mkdir iio
          tar xf iio.tar.gz -C iio --strip-components=1
          mkdir iio/build && cd iio/build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local ..
          make -j2
          sudo make install

      - name: Install libiio
        run: |
          wget -nv https://github.com/analogdevicesinc/libiio/releases/download/v0.23/macOS-10.15.pkg
          sudo installer -pkg macOS-10.15.pkg -target /
          ls -l /Library/Frameworks/iio.framework/iio
          ls -l /Library/Frameworks/iio.framework/Versions/Current
          ls -l /Library/Frameworks/iio.framework/Versions/0.23/iio
          file /Library/Frameworks/iio.framework/Versions/0.23/iio
          ln -s /Library/Frameworks/iio.framework/Versions/0.23/iio /usr/local/lib
          cp /Library/Frameworks/iio.framework/Versions/0.23/Headers/iio.h /usr/local/include

      - name: Install SDRPlay
        run: |
          wget -nv https://www.sdrplay.com/software/SDRplay_RSP_API-MacOSX-2.13.2.pkg
          sudo installer -pkg SDRplay_RSP_API-MacOSX-2.13.2.pkg -target /

      - run: python3 -m pip install -r data/requirements.txt
        working-directory: urh

      - name: Build extensions
        run: python3 setup.py build_ext --inplace --with-plutosdr
        working-directory: urh

      - name: Check native backends
        run: |
          python3 -m pip install .
          python3 data/check_native_backends.py
        working-directory: urh
