name: macos

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-10.15

    steps:
      - run: git clone https://github.com/jopohl/urh

      - name: Install SDR libs
        run: |
          brew tap pothosware/homebrew-pothos
          brew update
          brew install airspy hackrf librtlsdr libbladerf limesuite libiio portaudio uhd

      - run: python3 -m pip install -r data/requirements.txt
        working-directory: urh

      - name: Build extensions
        run: |
          export LIBRARY_PATH="$LIBRARY_PATH:$(brew --prefix)/lib"
          export C_INCLUDE_PATH="$C_INCLUDE_PATH:$(brew --prefix)/include"
          export CPP_INCLUDE_PATH="$CPP_INCLUDE_PATH:$(brew --prefix)/include"
          python3 src/urh/cythonext/build.py
        working-directory: urh

      - name: Check native backends
        run: |
          python3 -m pip install .
          python3 data/check_native_backends.py
        working-directory: urh
